import Arrow from '@/assets/icons/arrow.svg?react';
import InfoSvg from '@/assets/icons/info-icon.svg?react';
import ArrowWithTail from '@/assets/icons/arrow-with-tail.svg?react';
import EmailSvg from '@/assets/icons/email-icon.svg?react';
import BurgerMenu from '@/assets/icons/burger-menu-icon.svg?react';
import Cross from '@/assets/icons/cross-icon.svg?react';
import Share from '@/assets/icons/share-icon.svg?react';
import Calendar from '@/assets/icons/calendar-icon.svg?react';
import Download from '@/assets/icons/download-icon.svg?react';
import Reset from '@/assets/icons/reset-icon.svg?react';
import Map from '@/assets/icons/map-icon.svg?react';
import Video from '@/assets/icons/video-icon.svg?react';
import { withIcon } from './withIcon';

export const ArrowIcon = withIcon(Arrow);
export const InfoIcon = withIcon(InfoSvg);
export const ArrowWithTailIcon = withIcon(ArrowWithTail);
export const EmailIcon = withIcon(EmailSvg);
export const BurgerMenuIcon = withIcon(BurgerMenu);
export const CrossIcon = withIcon(Cross);
export const ShareIcon = withIcon(Share);
export const CalendarIcon = withIcon(Calendar);
export const DownloadIcon = withIcon(Download);
export const ResetIcon = withIcon(Reset);
export const MapIcon = withIcon(Map);
export const VideoIcon = withIcon(Video);
