name: CI
run-name: Lint, run coverage tests and build

on:
  push:
    branches: ['main', '6174-implement-githubaction-for-edge-deployment']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Install Yarn globally
        run: npm install -g yarn

      - name: Install dependencies  
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

      - name: Run linting 
        run: yarn run lint

      - name: Run coverage tests
        run: yarn run coverage

      - name: Build the front end
        run: yarn build
