name: lint and test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# cancel currently running workflow from the same PR or branch
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: npm install -g yarn
      - run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - run: yarn run lint
      - run: yarn run coverage
